all: red-spektrum-sz1.pdf red-spektrum-sz2.pdf red-spektrum-sz3.pdf

 
red-spektrum-sz1.pdf : 3er-fenster-sz1.plt
	gnuplot 3er-fenster-sz1.plt

 
red-spektrum-sz2.pdf : 3er-fenster-sz2.plt
	gnuplot 3er-fenster-sz2.plt

 
red-spektrum-sz3.pdf : 3er-fenster-sz3.plt
	gnuplot 3er-fenster-sz3.plt

