ALL: biegung-balken3.pdf biegung-balken1.pdf biegung-balken2.pdf

biegung-balken3.pdf: biegung-balken3.plt
	gnuplot biegung-balken3.plt

biegung-balken1.pdf: biegung-balken1-2.plt
	gnuplot biegung-balken1-2.plt

biegung-balken2.pdf: biegung-balken1-2.plt
	gnuplot biegung-balken1-2.plt