ALL: biegung-balken3.pdf biegung-balken1.pdf biegung-balken2.pdf echtzeitmittelung.pdf

biegung-balken3.pdf: biegung-balken3.plt
	gnuplot biegung-balken3.plt

biegung-balken1.pdf: biegung-balken1.plt
	gnuplot biegung-balken1.plt

biegung-balken2.pdf: biegung-balken2.plt
	gnuplot biegung-balken2.plt

echtzeitmittelung.pdf: echtzeitmittelung.plt
	gnuplot echtzeitmittelung.plt